PACKAGE_NAME="legion-nowake"
PACKAGE_VERSION="1.0"

MAKE[0]="make -C . KDIR=/lib/modules/${kernelver}/build KVER=${kernelver}"
CLEAN="make -C . clean KDIR=/lib/modules/${kernelver}/build KVER=${kernelver}"

BUILT_MODULE_NAME[0]="legion_nowake"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
